yarnPath: "./.yarn/releases/yarn-berry.js"

packageExtensions:
  "@webpack-cli/package-utils@*":
    dependencies:
      "cross-spawn": "*"
      "webpack-cli": "*"
  "webpack-cli@*":
    dependencies:
      "terser-webpack-plugin": "*"
      "@webpack-cli/serve": "*"
  "@webpack-cli/serve@*":
    dependencies:
      "command-line-args": "*"
      "webpack-cli": "*"
  "webpack-dev-server@*":
    dependencies:
      "webpack-cli": "*"
